[main]
path: /home/dvanerp/pepsi/results/he2rna_all_genes_crossval/
data_mode: tcga
# The following line aims at reproducing the exact same cross-validation as in the paper, but is not used when --single_run is passed
splits: /home/dvanerp/projects/HE2RNA_code/patient_splits.pkl

[data]
path_to_transcriptome: /home/dvanerp/pepsi/data/raw/tcga_rna/tcga_all_transcriptomes_tpm_10782.csv
path_to_data: /home/dvanerp/pepsi/data/processed/tcga_UNI2_supertiles_newclass_feb16.h5
keyfile_path: /home/dvanerp/pepsi/data/raw/manifests/new_keyfiles/new_master_keyfile.csv
genes: /home/dvanerp/pepsi/data/processed/cscc_rna/filtered_genes_tcgaANDcscc_csccmedian_pc_nc.csv

[architecture]
layers: 1024,1024
ks: 1,2,5,10,20,50,100
dropout: 0.25
nonlin: relu
device: cuda

[training]
max_epochs: 200
patience: 50
batch_size: 16
num_workers: 0

#WATCH OUT: set num_workers to 0 when using .h5 files!

[optimization]
optimizer: adam
lr: 3e-4