[main]
path: /home/dvanerp/pepsi/results/he2rna_all_genes_crossval/
data_mode: cscc
# The following line aims at reproducing the exact same cross-validation as in the paper, but is not used when --single_run is passed
# splits: /home/dvanerp/projects/HE2RNA_code/patient_splits.pkl
# no split needed for CSCC because we're finetuning from a TCGA model. UNI specifically because only CSCC UNI feats are available
use_saved_model: /home/dvanerp/pepsi/results/training_runs/JAN24_new_model_TCGA_UNI_allprojects_supertiles_mediangenes



[data]
path_to_transcriptome: /gpfs/work4/0/prjs1086/derm_shared/cscc/processed/rna_counts/txi.gene.counts.csv
path_to_data: /gpfs/work4/0/prjs1086/derm_shared/cscc/processed/he_packed_patch_feat_uni/rsm2/h5_files
keyfile_path: /gpfs/work4/0/prjs1086/derm_shared/cscc/doc/keyfiles/20260113_project_keyfile_anonymized_rsm2.csv,/gpfs/work4/0/prjs1086/derm_shared/cscc/processed/cd/DSQUAME_development_NCC_dataset_clean_no_newlines.csv
# genes: /home/dvanerp/pepsi/data/processed/cscc_rna/cscc_genes_to_keep.csv
# using the same genes as in TCGA because we're finetuning from that model
genes: /home/dvanerp/pepsi/data/processed/tcga_rna/tcga_genes_to_keep.csv 
project_column: study4


[architecture]
layers: 1024,1024
ks: 10,20,50,100,200,500,1000,2000,5000
dropout: 0.25
nonlin: relu
device: cuda
; ks: 1,2,5,10,20,50,100

[training]
# finetuning from TCGA model, so less epochs and patience
max_epochs: 150
patience: 30
batch_size: 4
num_workers: 8

#WATCH OUT: set num_workers to 0 when using .h5 files!

[optimization]
optimizer: adam
lr: 3e-4